version: b{build}
image: Visual Studio 2019
configuration: Release
platform: x64
before_build:
- cmd: nuget restore
build:
  project: ASFui.sln
  verbosity: minimal
artifacts:
- path: ASFui\bin\Release\ASFui.exe
  name: ASFui
